// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6FVMBFb-Qy5y-hhVVAARoYc56xg8bJhA',
    appId: '1:514525126341:android:7c745150a61a65d69ddaac',
    messagingSenderId: '514525126341',
    projectId: 'halsogourmet-d237a',
    storageBucket: 'halsogourmet-d237a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLpv439YQ4IQ5eXl127V837p7H7ayiEfg',
    appId: '1:514525126341:ios:d3abc0af52f134ab9ddaac',
    messagingSenderId: '514525126341',
    projectId: 'halsogourmet-d237a',
    storageBucket: 'halsogourmet-d237a.appspot.com',
    androidClientId: '514525126341-aih4o1hf3n6fb10kctg183alh14qaatu.apps.googleusercontent.com',
    iosClientId: '514525126341-gi8oqjn6pskartqob4ubj9275htg1jfl.apps.googleusercontent.com',
    iosBundleId: 'com.halsogourmet.app',
  );
}
